stages: 
  - release
  - publish

default:
  image: registry.gitlab.com/medicines-discovery-catapult/informatics/docker-images/ci/r:latest

publish-unstable:
  stage: publish
  script:
    - R -e "devtools::install_deps(dependencies = TRUE)"
    - source <(cictl config env)
    - R CMD build . --no-build-vignettes --no-manual
    - PACKAGE_NAME="mdcworld_$NEXT_TAG.tar.gz"
    - PACKAGE_URL="https://nexus.wopr.inf.mdc/repository/r-hosted/src/contrib/$PACKAGE_NAME"
    - curl -k -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file $PACKAGE_NAME $PACKAGE_URL
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-stable:
  stage: publish
  script:
    - R -e "devtools::install_deps(dependencies = TRUE)"
    - source <(cictl config env)
    - R CMD build . --no-build-vignettes --no-manual
    - PACKAGE_NAME="mdcworld_$LATEST_TAG.tar.gz"
    - PACKAGE_URL="https://nexus.wopr.inf.mdc/repository/r-hosted/src/contrib/$PACKAGE_NAME"
    - curl -k -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file $PACKAGE_NAME $PACKAGE_URL
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  script:
    - cictl exec release r R
  only:
    - main
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
